---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexa.
--- DateTime: 18/05/2022 19:07
---

fx_version "adamant"
game "gta5"

author "KraKss"
description "Weapon shop RageUI V2"
version "1.0"

shared_scripts {
    "shared/config.lua",
}

client_scripts {
    -------------- RUI V2 --------------
    "RageUI/RMenu.lua",
    "RageUI/menu/RageUI.lua",
    "RageUI/menu/Menu.lua",
    "RageUI/menu/MenuController.lua",
    "RageUI/components/*.lua",
    "RageUI/menu/elements/*.lua",
    "RageUI/menu/items/*.lua",
    "RageUI/menu/panels/*.lua",
    "RageUI/menu/windows/UIHeritage.lua",
    "client/*.lua",
}

server_scripts {
    "server/sv.lua",
}